### user signup
POST http://127.0.0.1:1212/api/user/signup HTTP/1.1
Content-Type: application/json

{
"userName":"new1123321","password":"0000", "email":"new1@123123123", "isUnlimited": true,"image": "123","isActive": true
}
### update user info
PATCH  http://127.0.0.1:1212/api/user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5ldyIsInVzZXJJRCI6IjY0OTMxY2Q5MTY4NWFiZDAyNmY2OGQ0MCIsImlhdCI6MTY4NzM2ODM2MX0._tlJ3VQ1j7GCdteeiD4XYceMS5T5cLadMivQUwr_Z8A

{
    "data": {"userName":"update yee", "email":"123321"}
}

###soft delete user
DELETE   http://127.0.0.1:1212/api/user/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5ldyIsInVzZXJJRCI6IjY0OTMxY2Q5MTY4NWFiZDAyNmY2OGQ0MCIsImlhdCI6MTY4NzM2ODM2MX0._tlJ3VQ1j7GCdteeiD4XYceMS5T5cLadMivQUwr_Z8A


### user login
POST http://127.0.0.1:1212/api/user/login HTTP/1.1
Content-Type: application/json

{"userName":"new1","password":"0000"}
### get profile
GET  http://127.0.0.1:1212/api/user/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVwZGF0ZSB5ZWUiLCJ1c2VySUQiOiI2NDkzMWNkOTE2ODVhYmQwMjZmNjhkNDAiLCJpYXQiOjE2ODczNjk2OTZ9.ikjFYqsXSixksQ3WWOd3tHFMV2FhJbOHXEOJVBSKmhU


### company signup
POST http://127.0.0.1:1212/api/company/signup HTTP/1.1
Content-Type: application/json

{
"companyName":"new123","password":"0000", "email":"new1@123321", "image": "123"
}

### company login
POST http://127.0.0.1:1212/api/company/login HTTP/1.1
Content-Type: application/json

{"companyName":"updatedName","password":"0000"}

### get conpany profile
GET  http://127.0.0.1:1212/api/company/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55TmFtZSI6ImVkZWthIiwiY29tcGFueUlEIjoiNjQ5MzY4ZDU2MWVjMjYwMTQ1ZGJkZmRkIiwiaWF0IjoxNjg3MzgzMjgxfQ.A3kgd2MUZswqqjsWbkQ01W0QIcBJAkeLW0rqpteEIiM


###update company
PUT  http://127.0.0.1:1212/api/company/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55TmFtZSI6InVwZGF0ZWROYW1lIiwiY29tcGFueUlEIjoiNjQ5MzNjYTFiODljMjM3NzJhMGYyMjgwIiwiaWF0IjoxNjg3Mzc0MTY4fQ.nUEppyUxtpcGBWAbMq4mhhnWoAdORCSussPoxdRgD1Y

{"data":{"companyName":"updatedName", "email":"new1@123", "image": "123"}}

###delete company
DELETE http://127.0.0.1:1212/api/company/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55TmFtZSI6InVwZGF0ZWROYW1lIiwiY29tcGFueUlEIjoiNjQ5MzNjYTFiODljMjM3NzJhMGYyMjgwIiwiaWF0IjoxNjg3Mzc0MTY4fQ.nUEppyUxtpcGBWAbMq4mhhnWoAdORCSussPoxdRgD1Y

### create project
POST http://127.0.0.1:1212/api/project/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVwZGF0ZSB5ZWUiLCJ1c2VySUQiOiI2NDkzMWNkOTE2ODVhYmQwMjZmNjhkNDAiLCJpYXQiOjE2ODczODY5NzJ9.lkNqcH1zZJNRBlrDzDSfp30R71hQ6ar9SzFdhBmVazM

{"projectName":"new Project4", "isActive":true}

###  finish project
DELETE  http://127.0.0.1:1212/api/project/finish HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVwZGF0ZSB5ZWUiLCJ1c2VySUQiOiI2NDkzMWNkOTE2ODVhYmQwMjZmNjhkNDAiLCJpYXQiOjE2ODczODY5NzJ9.lkNqcH1zZJNRBlrDzDSfp30R71hQ6ar9SzFdhBmVazM
Content-Type: application/json

{"projectName":"new Project4"}
### get project
GET http://127.0.0.1:1212/api/project/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5ldzEiLCJ1c2VySUQiOiI2NDkzMjJjYzA3ZWE3NjcyZjhhZGJhYTEiLCJpYXQiOjE2ODczODQ0ODZ9.z6nE20gyas4na2wcxeJ7OZiZE1WMUWtp3v9UuKtQUV4


### create user Product
POST http://127.0.0.1:1212/api/userproduct/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVwZGF0ZSB5ZWUiLCJ1c2VySUQiOiI2NDkzMWNkOTE2ODVhYmQwMjZmNjhkNDAiLCJpYXQiOjE2ODczODY5NzJ9.lkNqcH1zZJNRBlrDzDSfp30R71hQ6ar9SzFdhBmVazM

{"lat": 51.38696757539427,
  "lon": 12.388481425497321,
  "companyProductID": "new",
  "projectID": "weweqwrwqw"
}



### update user Product

PATCH  http://127.0.0.1:1212/api/userproduct/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVwZGF0ZSB5ZWUiLCJ1c2VySUQiOiI2NDkzMWNkOTE2ODVhYmQwMjZmNjhkNDAiLCJpYXQiOjE2ODczODY5NzJ9.lkNqcH1zZJNRBlrDzDSfp30R71hQ6ar9SzFdhBmVazM

{"data":{"lat": 0.50,
  "lon": 12.12,
  "companyProductID": "update",
  "projectID": "weweqwrwqw","createBy":"64931cd91685abd026f68d40"
}, "id" :"64942025a22bea91dcc0d91e"}

### Delete product
DELETE  http://127.0.0.1:1212/api/userproduct/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVwZGF0ZSB5ZWUiLCJ1c2VySUQiOiI2NDkzMWNkOTE2ODVhYmQwMjZmNjhkNDAiLCJpYXQiOjE2ODczODY5NzJ9.lkNqcH1zZJNRBlrDzDSfp30R71hQ6ar9SzFdhBmVazM

{"id":"64941a009a45ce49eccbfdc3"}

### get product list
POST  http://127.0.0.1:1212/api/userproduct/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVwZGF0ZSB5ZWUiLCJ1c2VySUQiOiI2NDkzMWNkOTE2ODVhYmQwMjZmNjhkNDAiLCJpYXQiOjE2ODczODY5NzJ9.lkNqcH1zZJNRBlrDzDSfp30R71hQ6ar9SzFdhBmVazM
Content-Type: application/json

{"projectID":"weweqwrwqw"}

### company create product
POST http://127.0.0.1:1212/api/companyproduct/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55TmFtZSI6InJld2VuZXciLCJjb21wYW55SUQiOiI2NDkzNzBmNWZjYzNjZDhmMzVkNzA0NmYiLCJpYXQiOjE2ODc0MzYyNDR9.4uo3SnKFHabmKDPClEWfS9oRs_xk7rEgzWrG5lWgN-Y
Content-Type: application/json

{"area": 1,
  "orientation": "N",
  "tilt": 2,
  "productName": "OeO111Piyan"}

### update company Product

PATCH  http://127.0.0.1:1212/api/companyproduct/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55TmFtZSI6InJld2VuZXciLCJjb21wYW55SUQiOiI2NDkzNzBmNWZjYzNjZDhmMzVkNzA0NmYiLCJpYXQiOjE2ODc0MzYyNDR9.4uo3SnKFHabmKDPClEWfS9oRs_xk7rEgzWrG5lWgN-Y

{"data":{"area": 3,
  "orientation": "N",
  "tilt": 2,
  "productName": "update product","createBy":"649370f5fcc3cd8f35d7046f"
}, "id" :"64958c190fe1481c23701e06"}

### Delete company product
DELETE http://127.0.0.1:1212/api/companyproduct/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55TmFtZSI6InJld2VuZXciLCJjb21wYW55SUQiOiI2NDkzNzBmNWZjYzNjZDhmMzVkNzA0NmYiLCJpYXQiOjE2ODc0MzYyNDR9.4uo3SnKFHabmKDPClEWfS9oRs_xk7rEgzWrG5lWgN-Y

{"id" :"64944b5949cdc800ea5613a3"}


### User get company Product list

GET http://127.0.0.1:1212/api/companyproduct/user-list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im5ldzEiLCJ1c2VySUQiOiI2NDkzMjJjYzA3ZWE3NjcyZjhhZGJhYTEiLCJpYXQiOjE2ODc0NDE3ODZ9.FkjhSWSlAFMKqYS8xW2mirMgNAQOsWO1yo6b-QRPb-Y


### Company get product list
GET http://127.0.0.1:1212/api/companyproduct/company-list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55TmFtZSI6InJld2VuZXciLCJjb21wYW55SUQiOiI2NDkzNzBmNWZjYzNjZDhmMzVkNzA0NmYiLCJpYXQiOjE2ODc0MzYyNDR9.4uo3SnKFHabmKDPClEWfS9oRs_xk7rEgzWrG5lWgN-Y


###
GET  https://api.openweathermap.org/data/2.5/onecall?lat=50.828176307268556&lon=12.922558179117553&appid=ca20b15c0e2800058d1de6ba9abe60f6 HTTP/1.1

### 
Post http://127.0.0.1:1212/api/project/update-now HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNoLWxlZTA2MjYiLCJ1c2VySUQiOiI2NDk5NzM4ODFhMzhjZGUxODM1M2JiZjciLCJpYXQiOjE2ODc3NzgxOTV9.vxPog0MoUB6Kz6RcjclxUwV05IPUZKPAw-9NU7G7E9M


