### get user list
GET  http://13.50.5.249:3000/weather/user  HTTP/1.1

### create user account
POST http://13.50.5.249:3000/weather/user HTTP/1.1
Content-Type: application/json

{"username": "OeO",
"email": "OeO@gmail.com",
"password": "0000"}
###
PATCH http://13.50.5.249:3000/weather/user/6490d604498f013b04795b4f HTTP/1.1
Content-Type: application/json

{"username": "ch-lee",
"email": "ch-lee@gmail.com",
"password": "test123321"}

### delete account
DELETE http://13.50.5.249:3000/weather/user/648f1ee2e395e458b3589a1b HTTP/1.1

###update user account

PATCH http://13.50.5.249:3000/weather/user/648f1ee2e395e458b3589a1b HTTP/1.1

{"username": "test123321",
"email": "test123321@gmail.com",
"password": "$2b$10$2Y7DJCO3DEcfaJ7KDqgMlOHXDIhmOrOO.yRp0thIMMlLqjbpTwTQ2"}

### project

GET http://13.50.5.249:3000/weather/project/ HTTP/1.1

###user's project
GET http://13.50.5.249:3000/weather/project HTTP/1.1
Content-Type: application/json

{
 "userid": "weather123"}

###login
POST http://13.50.5.249:3000/weather/user/login HTTP/1.1
Content-Type: application/json

{"username": "OeO",
"password": "OeO"}